---

- meta: flush_handlers

- name: Install required packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - aptly
    - gnupg2
    - python-dev
    - python-pip
    - python-gnupg
    - libffi-dev
    - git-core
    - python-pexpect
    - apache2

- name: Upgrade Pip
  pip:
    name={{ item }}
    state=latest
  with_items:
    - requests[security]
    - pip

- name: Install Pxul
  pip:
    name="git+https://github.com/badi/pxul.git@v2.0#egg=pxul"
    state=present

- name: Import the mirror keys
  sudo: no
  gpg_import:
    key: "{{ item.trusted_key }}"
    keyring: "{{ item.keyring | default('trustedkeys.gpg') }}"
    keyserver: "{{ item.keyserver | default('keys.gnupg.net') }}"
  with_items: mirrors

- name: Create the aptly mirrors
  sudo: no
  aptly:
    subject: mirror
    verb: create
    name: "{{ item.name }}"
    uri: "{{ item.uri }}"
    distribution: "{{ item.distribution }}"
    components: "{{ item.components }}"
    architectures: "{{ item.architectures | default(None)}}"
  with_items: mirrors

- name: Update the aptly mirrors
  sudo: no
  aptly:
    subject: mirror
    verb: update
    name: "{{ item.name }}"
    within: "{{ item.within | default(0) }}"
  with_items: mirrors

- name: Create snapshots
  sudo: no
  aptly:
    subject: snapshot
    verb: create
    name: "{{ item.name }}"
    within: "{{ item.within | default(0) }}"
  with_items: mirrors

- name: Publish snapshots
  sudo: no
  aptly:
    subject: publish
    verb: snapshot
    name: "{{ item.name }}"
    gpg_passphrase: "{{ mirror_gpg_password | default(None) }}"
  with_items: mirrors

- name: Configure webserver
  template:
    src: mirrors.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart webserver
